### ISSUE TITLE
How to install on Android? 

### ISSUE THREAD

**Issue by JuergenKaettnis** [macrojd/tag-summary#3]
Hi there,
I really like the idea of the plugin. And it would suit very much my work flow. I read something, import the highlights to Obsidian, and then mostly use tags as a kind of developing categories. Unfortunately, I do not understand how to install the plugin. With BRAT plugin it didn't work. I got a message like: "The plugin is already on a list for Beta testing." or something the like. Does the plugin work on Android devices at all? Where can I find the necessary files to download? And what is the name of the subfolder for the plugin supposed to be?

Would be real kind, if you could give me a small push to sum up all my diverse tags.😉 Hope a short answer would be enough.

**Comment by macrojd** [comment]
Hi. I haven't try it on Android or Windows yet, but it should work fine since all I do is to read the files and show the result (there are no changes on the interface or anything system related). I installed it with BRAT and was working with no errors. Make sure that the plugin is enabled and you got version 1.1.0. After installing, you still have to go to Community Plugins and enable it. Right now I'm trying to get it into the Community Plugins, so people can search for it and give me more feedback. I'll let you know if I find something else that can help you.
