### ISSUE TITLE
Expand function to different objects

### ISSUE THREAD

**Issue by dxcore35** [macrojd/tag-summary#6]
Please do not limit this plugin only to TAGS!

Add summary based on:
- inline YAML field
- key word
- combination of words
- heading name

It will have same function but apply to different kind of objects. And expand the usefulness of summaries. For me the plugin can be easily called just "Obsidian summary".

**Comment by macrojd** [comment]
Hi. Unfortunately there could be some performance issues. At first, I programmed the plugin to scan every file, but it was rejected. Obsidian developers asked me to check first whether the files contain the tags selected by the user. Obsidian offers a list with the tags included in each file, so I can check that list and only process the files if they contain the tags selected by the user. If I try to look for words or anything else, the plugin will be rejected again. Maybe Obsidian developers decide to incorporate this feature right into the software later if the plugin becomes successful.

**Comment by dxcore35** [comment]
"but it was rejected" - there are no judges to reject something. You can write whatever plugin you like, I don't understand this statement. I don't understand you need to scan the text regardless to extract the text. Also Dataview plugin is scanning the notes based on YAML fields and it is lighting fast.

**Comment by macrojd** [comment]
Hi. A few days after I published the plugin, a developer told me that it was too resource intensive to search for tags in every file. He asked me to search for the list of tags first before processing every file and other minor changes. I introduced the changes right away, but it took around four months for the plugin to be approved and added to the community. At the same time, I saw plugins developed by other people included in a week or two. I don't know how Obsidian developers work, but I interpret that as a rejection and a risk. I developed the plugin because I needed to search for tags in my vault, but I don't need a plugin to search for words, so I could be working for days to develop the changes with the risk of not being accepted and for no benefits. For instance, yesterday someone that speaks Russian told me that the plugin didn't work. Then he realized that it didn't work in Cyrillic. I though about making the changes right away, but I never created Regular Expressions for other languages, so it could take me a few days to figure that out and then a few more days to develop and test everything to make sure it works. Unfortunately, I don't have the time to do it right now. Maybe in a few months I make the time to work on that, because I know there won't be any issues, but to expand the plugin to search for words has the risk of rejection or performance issues (according to Obsidian developers), and I don't have the time to deal with that. My advice is to post the suggestion on Obsidian forums. Maybe someone can pick up my plugin and develop another one that does what you need.

**Comment by mnaoumov** [comment]
@macrojd see #10
